### ISSUE TITLE
3D examples

### ISSUE THREAD

**Issue by rmodrak** [rmodrak/seisflows#31]
Hi Ryan,

Thanks for the help!

I used the 2-D example in SeisFlows months ago, it works well. However, they haven't provided a 3-D example for specfem3d nor specfem3d_globe at that time. That is why I have to write scripts of iterative inverison with specfem3d by myself.

As reminded by you, they have already launched 3-D examples for Cartesian and Global version. Cheers ! However, the 3-D examples are only available for local user with account on tiger, which I am not. I have taken your suggest to use MODEL=gll for updating models, it works well. Thanks!

In the meantime, do you have some materials about how to use src/tomography codes and I will appreciate if you can provide me some. By the way, could it possible for non-local user like me to get the two 3-D examples for Cartesian and Global version from Seisflows?

Best regards,
Kai

**Comment by rmodrak** [comment]
Hi Kai,

I've copied the 3D Cartesian example we use on our local cluster to http://tigress-web.princeton.edu/~rmodrak/3dAcoustic/checkers. You might be able to get it to work by downloading SPECFEM3D commit b555982 and compiling and substituting your own (machine dependent) binaries. Minor changes to the system interface might be needed. Do you have at least 16 cores on the node you'll be submitting from? You could probably run with as few as four cores, but you'd have to modify some things.

Also, I've copied the 3D global example we use to http://tigress-web.princeton.edu/~rmodrak/Examples3dGlobe/mideast. This one is a lot more expensive than the 3D Cartesian examples, and it's been longer since I tested it, so you may be better off starting with the 3D Cartesian example.

Compared with the 2D checkerboard inversion, the 3D test cases are quite expensive, so they are not designed to run as long. If you make it to the line search, then be assured everything is working properly, even if you get a line search error.

Best,
Ryan

**Comment by yuefeng9330** [comment]
Hi Ryan,

Thanks! 
Right now I am trying to do elastic inversion with ambient noise data using ADJOINT_TOMOGRAPHY_TOOLS (struggling for about one month to figure out how to use them, maybe not). I would like to learn the 3D Cartesian examples and apply it to my research.

Best,
Kai

**Comment by rmodrak** [comment]
Sounds like an enjoyable project.  Could you let me know how goes with the 3D Cartesian example?  Good luck!

**Comment by yuefeng9330** [comment]
Sure. For this moment, I prefer to finish my own scripts of waveform inversion using tomography tools in specfem3d. After that, I'd like to use Seisflows to do a same work for comparison. If all goes well, I would be very glad to share the work with you and your group.

**Comment by rmodrak** [comment]
Sounds like a great plan.  For other users' reference, let me link to the [original thread] (https://github.com/geodynamics/specfem3d/issues/732) on the SPECFEM3D repo.

**Comment by dkzhangchao** [comment]
Kai，
I think that our project is similar, however, my case is 2D. Maybe we can discuss for this
attached is my email: dkzhangchao@gmail.com
thanks

Chao
