### ISSUE TITLE
marmousi example not working

### ISSUE THREAD

**Issue by rmodrak** [rmodrak/seisflows#81]
```
Dear Dr Ryan,

I am trying to run the examples 2D at seisflow and i am not able to run.

My tests are sucesfuly done and i realise that woulb be impossible to run since the file legacy,py it is not at the package for download.

Also i found other package at https://github.com/DmBorisov/SeisFlows_tunnel but it is also not working to run this examples.

Could you please help me?

I am very interest to use seisflow, thank you very much for your time.
```

**Comment by rmodrak** [comment]
Hi Kati,

Thanks for trying the package and letting me know about this problem.  If I understand, the checkerboard test included in the documentation is working but the marmousi example is not.

As a first attempt at the getting the marmousi example to work, feel free to try the updated parameter file located here:
http://tigress-web.princeton.edu/~rmodrak/2dElastic/marmousi_offshore/parameters.py
All I did was change `PREPROCESS` and `FORMAT` and remove several old parameters. 

Because I graduated and just started a new job, I haven't been able to investigate thoroughly or update the online documentation, but I hope to eventually.  Sorry for the inconvenience and thanks for your patience.

As for Dmitry's package, I didn't know that it existed!  It might possibly be due for deletion because it is rather old and not even a fork or branch of the main repository.   Feel free however to ask @DmBorisov about it.

Best wishes,
Ryan

**Comment by rmodrak** [comment]
P.S.  Are you familiar by chance with how to create models in SPECFEM2D?  No worries if you are not.

(For the brave, it might be possible to use the checkerboard test case as a model to create other 2D inversion examples, provided one has experience with the SPECFEM2D solver.  SPECFEM2D is a hard package to use in my opinion because it's quick-and-dirty, never having received its own funding.   My hope is eventually SALVUS might be used in place of SPECFEM2D, but that's unlikely to happen soon unfortunately.)

**Comment by katigeophysics** [comment]
Thank you very much Ryan. It is running now. 
I would like to know if you have some material that explains seisflow about the files, structure... like a manual. 
I am getting familiar with SPECFEM2D and 3D and the manual it is helping a lot. 
Thanks again!

**Comment by rmodrak** [comment]
There is a usage overview located here,
https://github.com/rmodrak/seisflows/blob/master/docs/manual/manual.rst,
which I hope to eventually expand this into a longer user manual.

While no substitute for a manual,  several outside users have become pretty experienced with the package by spending a few days analyzing source code.  Compared with about 10^5 lines of code in SPECFEM3D, seisflows has only about 10^4 lines of code, so in some ways seisflows might be a bit easier learn.

**Comment by katigeophysics** [comment]
Thank you. Could you please share your recently article submitted: Modrak, R., Borisov, D., Lefebvre, M., and Tromp, J., The SeisFlows framework for waveform inversion: from 2D rapid prototyping to 3D large-scale production, Computers and Geosciences, Submitted. (2017) ? 
Regards, Kati.

**Comment by katigeophysics** [comment]
Just another question. How can i generate the files .bin in the folder model_init and model_true?

**Comment by rmodrak** [comment]
Excellent question regarding model files.  Since this question probably deserves its own issue, let me close the current one and open issue #83.
